CMPUT301F20T05/CriEngine

client/app/src/main/java/com/example/criengine/Book.java
client/app/src/main/java/com/example/criengine/DatabaseWrapper.java
client/app/src/main/java/com/example/criengine/MainActivity.java
client/app/src/main/java/com/example/criengine/MyBooksActivity.java

- integrate MyBooksActivity with real online books
- add auto sign in config because I was sick of logging in manually
- ![image](https://user-images.githubusercontent.com/10664941/97605816-b972c600-19d4-11eb-95b7-559e42506b44.png)

feat: integrate MyBooksActivity with real online books

---

client/app/src/main/java/com/example/criengine/Activities/MainActivity.java

- Fixed the issue where the database would not load.
- N/A
- N/A

fix: solve mainActivity bug

---

client/app/src/test/java/com/example/criengine/NotificationUnitTest.java

- Added notification class tests.
https://github.com/CMPUT301F20T05/CriEngine/issues/70
~~- [ ] (**For later in project**) Integration tests written?~~
~~- [ ] Java docs written?~~

feat: add Notification tests

---

client/app/src/main/AndroidManifest.xml
client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFilterFragment.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
client/app/src/main/res/layout/activity_my_books.xml

- Swapped it to now be a part of the nav-activity.
N/A

fix: My-Books-List is now a fragment

---

client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Fragments/NotificationFragment.java

- Changed it into a fragment so it can be accessed through the nav bar.
N/A

fix: notification activity is now a fragment.

---

client/app/build.gradle
client/app/src/androidTest/java/com/example/criengine/LoginScreenTest.java

- Added intent tests for the login screen.
https://github.com/CMPUT301F20T05/CriEngine/issues/95

feat: add login intent tests

---

client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java
client/app/src/main/java/com/example/criengine/Fragments/ProfileFragment.java
client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java
client/app/src/main/java/com/example/criengine/Fragments/RootFragment.java
client/app/src/main/java/com/example/criengine/Interfaces/IOnBackPressed.java

- made MyProfile as a fragment
- renamed initRootFrag() to getFragmentLayout()
-

feat: make profile a fragment

---

client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/BookActivity.java
client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/MyProfileActivity.java
client/app/src/main/java/com/example/criengine/Activities/ProfileActivity.java
client/app/src/main/java/com/example/criengine/Activities/RequestActivity.java
client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Activities/UserProfileActivity.java
client/app/src/main/java/com/example/criengine/Adapters/BorrowerBooksListAdapter.java
client/app/src/main/java/com/example/criengine/Adapters/MyBooksAdapter.java
client/app/src/main/java/com/example/criengine/Adapters/NotificationAdapter.java
client/app/src/main/java/com/example/criengine/Adapters/RequestsForBookAdapter.java
client/app/src/main/java/com/example/criengine/Database/DatabaseWrapper.java
client/app/src/main/java/com/example/criengine/Database/GoogleBooksWrapper.java
client/app/src/main/java/com/example/criengine/Fragments/BottomNavFragment.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFilterFragment.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java
client/app/src/main/java/com/example/criengine/Fragments/NotificationFragment.java
client/app/src/main/java/com/example/criengine/Fragments/ProfileFragment.java
client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java
client/app/src/main/java/com/example/criengine/Fragments/RootFragment.java
client/app/src/main/java/com/example/criengine/Interfaces/IOnBackPressed.java
client/app/src/test/java/com/example/criengine/BookUnitTest.java
client/app/src/test/java/com/example/criengine/NotificationUnitTest.java
client/app/src/test/java/com/example/criengine/ProfileUnitTest.java

- Added all missing java docs. This project is now up-to-date will all missing javaDocs.
- Also cleaned up unneeded imports

fix: added all missing javaDocs

---

client/app/src/main/res/layout/activity_requests_for_book.xml

- Added in the nav bar fragment for the requests-for-book activity
-

fix: added in the nav bar for requestsForBook

---

client/app/src/androidTest/java/com/example/criengine/AddABookTest.java

feat: add a book intent tests

---

client/app/src/androidTest/java/com/example/criengine/NotificationTest.java

- Added intent tests for navigating to the notification fragment
-

feat: add notifications intent test

---

client/app/src/androidTest/java/com/example/criengine/MyRequestTest.java

- Added intent tests for my-requests fragment.
-

feat: add my request intent tests

---

client/app/src/androidTest/java/com/example/criengine/MyProfileTest.java

- Added tests for my profile fragment.
-

feat: add my profile intent tests

---

client/app/src/androidTest/java/com/example/criengine/ViewMyBookTest.java

- Added intent tests for view my book activity
-

feat: add intent tests for view my book activity

---

client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java

- Saving will now return to the main screen
- 
https://github.com/CMPUT301F20T05/CriEngine/issues/124

fix: saving will automatically return to the main screen

---

client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java

- Fixed: Test PR removed a required import

fix: add required imports

---

client/app/src/main/AndroidManifest.xml
client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Adapters/BorrowerBooksListAdapter.java
client/app/src/main/java/com/example/criengine/Fragments/ErrorFragment.java
client/app/src/main/res/layout/activity_error.xml

- added new blank fragment to search page to indicate WIP
- page is named error fragment to be reused later for error pages
- disabled borrower book buttons pending implementation
-

feat: Added blank page to search and disabled book buttons

---

client/app/src/main/res/layout/component_profile.xml
client/app/src/main/res/values/strings.xml

- change the bio text to a hint
-

feat: change bio text to hint

---

client/app/src/main/java/com/example/criengine/Adapters/BorrowerBooksListAdapter.java
client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java
client/app/src/main/res/layout/activity_request.xml
client/app/src/main/res/values/strings.xml

- This was supposed to be a bigger change but we dont have the necessary activities for it just yet.
- I put in some comment fixes though.

 fix: fragment now matches the figma

---

client/app/src/androidTest/java/com/example/criengine/AddABookTest.java
client/app/src/androidTest/java/com/example/criengine/LoginScreenTest.java
client/app/src/androidTest/java/com/example/criengine/MyBooksListTest.java
client/app/src/androidTest/java/com/example/criengine/MyProfileFragmentTest.java
client/app/src/androidTest/java/com/example/criengine/MyRequestTest.java
client/app/src/androidTest/java/com/example/criengine/NotificationTest.java
client/app/src/androidTest/java/com/example/criengine/ViewMyBookTest.java
client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java

- Tests now use "intentTestingUser@email.com" user, which should always be empty
-

fix: change tests to use intentTest login

---

client/app/src/androidTest/java/com/example/criengine/RootActivityTest.java
client/app/src/main/res/layout/activity_request.xml
client/app/src/main/res/values/strings.xml

- adds RootActivity intent test
- fixes the last menu item from "My profile" to "My Profile" .. capital P
- adds an id to the My Requests layout (for testing purposes)

feat: add RootActivity intent test

---

client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFilterFragment.java

- Improved the filter to allow for any text to be displayed.
- Does not close the filter menu if you click outside it

fix: improved the filter

---

client/app/src/main/AndroidManifest.xml
client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
client/app/src/main/java/com/example/criengine/Activities/RegisterAccount.java
client/app/src/main/res/layout/activity_login.xml
client/app/src/main/res/layout/register_account.xml
client/app/src/main/res/values/colors.xml
client/app/src/main/res/values/strings.xml

- Added the registration activity.
https://github.com/CMPUT301F20T05/CriEngine/issues/141

feat: add registration activity

---

client/app/src/androidTest/java/com/example/criengine/MyProfileFragmentTest.java
client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
client/app/src/main/java/com/example/criengine/Activities/MyProfileActivity.java
client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java
client/app/src/main/res/layout/activity_my_profile.xml
client/app/src/main/res/values/strings.xml

- ability to logout from MyProfileFragment
-

feat: logout button in MyProfileFragment

---

client/app/src/main/java/com/example/criengine/Activities/NonOwnerBookViewActivity.java

- Gets and updates information from the database.
- 
https://github.com/CMPUT301F20T05/CriEngine/issues/156

fix: non-owner book view retreives and updates the database

---

client/app/src/androidTest/java/com/example/criengine/AddABookTest.java
client/app/src/androidTest/java/com/example/criengine/LoginScreenTest.java
client/app/src/androidTest/java/com/example/criengine/MyBooksListTest.java
client/app/src/androidTest/java/com/example/criengine/MyProfileFragmentTest.java
client/app/src/androidTest/java/com/example/criengine/MyRequestTest.java
client/app/src/androidTest/java/com/example/criengine/NotificationTest.java
client/app/src/androidTest/java/com/example/criengine/RootActivityTest.java
client/app/src/androidTest/java/com/example/criengine/ViewMyBookTest.java
client/app/src/main/java/com/example/criengine/Activities/AddBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/CameraActivity.java
client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java
client/app/src/main/res/layout/activity_add_book.xml
client/app/src/main/res/values/strings.xml

- Corrected the broken tests and improved some of the others.
- Made the add-a-book screen have the ability to add an image. (Needs the camera PR to be merged in before continuing work on it)
- New screen for add-a-book
- New Alert dialog when you click the save button.
https://github.com/CMPUT301F20T05/CriEngine/issues/157

fix: intent tests pass & improved add-a-book activity

---

client/app/src/androidTest/java/com/example/criengine/AddABookTest.java
client/app/src/androidTest/java/com/example/criengine/CameraScreenTest.java
client/app/src/androidTest/java/com/example/criengine/LoginScreenTest.java
client/app/src/androidTest/java/com/example/criengine/MyBooksListTest.java
client/app/src/androidTest/java/com/example/criengine/MyProfileFragmentTest.java
client/app/src/androidTest/java/com/example/criengine/MyRequestTest.java
client/app/src/androidTest/java/com/example/criengine/NotificationTest.java
client/app/src/androidTest/java/com/example/criengine/RootActivityTest.java
client/app/src/androidTest/java/com/example/criengine/TestUtilityMethods.java
client/app/src/androidTest/java/com/example/criengine/ViewMyBookTest.java
client/app/src/main/java/com/example/criengine/Activities/CameraActivity.java
client/app/src/main/res/layout/activity_camera.xml

- Proper intent tests make books, run tests, and then delete the book leaving a clean slate.
- Also removed the cancel button from the camera screen.
- Just removed the cancel button, thats basically it ;-;

fix: better tests

---

client/app/build.gradle
client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
client/app/src/main/java/com/example/criengine/Fragments/MyProfileFragment.java
client/app/src/main/java/com/example/criengine/Fragments/NotificationFragment.java
client/app/src/main/java/com/example/criengine/Fragments/ProfileFragment.java
client/app/src/main/java/com/example/criengine/Fragments/RequestedBooksFragment.java
client/app/src/main/java/com/example/criengine/Fragments/RootFragment.java
client/app/src/main/java/com/example/criengine/Fragments/SearchBooksFragment.java
client/app/src/main/res/layout/activity_my_books.xml
client/app/src/main/res/layout/activity_my_profile.xml
client/app/src/main/res/layout/activity_notification.xml
client/app/src/main/res/layout/activity_request.xml
client/app/src/main/res/layout/activity_root.xml
client/app/src/main/res/layout/fragment_search_books.xml

- Added swipe refresh layouts to each fragment
- Reload the entire activity

feat: add pull refresh

---

client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/SelectGeopage.java
client/app/src/main/java/com/example/criengine/Adapters/RequestsForBookAdapter.java
client/app/src/main/java/com/example/criengine/Database/DatabaseWrapper.java
client/app/src/main/java/com/example/criengine/Objects/Book.java
client/app/src/main/java/com/example/criengine/Objects/Profile.java

- Fix requestlist changes
- Add method for getting LatLon from a book
- #29

fix: requestlist now shows username not userID

---

client/app/src/androidTest/java/com/example/criengine/TestUtilityMethods.java
client/app/src/main/java/com/example/criengine/Activities/LoginActivity.java
client/app/src/main/java/com/example/criengine/Activities/MyBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
client/app/src/main/java/com/example/criengine/Activities/RootActivity.java
client/app/src/main/java/com/example/criengine/Adapters/BorrowerBooksListAdapter.java
client/app/src/main/java/com/example/criengine/Adapters/MyBooksAdapter.java
client/app/src/main/java/com/example/criengine/Adapters/NotificationAdapter.java
client/app/src/main/java/com/example/criengine/Adapters/RequestsForBookAdapter.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java

- Pressing the back button while in the login screen will now close the app 
- Pressing back while looking at requesters for a book will now return to the previous screen. No need to override the back button because its only ever accessible from two locations.
- Deleted unnecessary class headers.
- Deleting a book will delete the book before returning to the home screen.
- N/A

fix: lots of bug fixes

---

client/app/src/main/java/com/example/criengine/Adapters/BorrowerBooksListAdapter.java

- Capitalize the requests status in BorrowerlistAdapter
-

fix: capitalize requests status

---

client/app/src/main/java/com/example/criengine/Activities/RequestsForBookActivity.java
client/app/src/main/java/com/example/criengine/Fragments/MyBooksListFragment.java
client/app/src/main/res/layout/activity_my_books.xml
client/app/src/main/res/layout/activity_requests_for_book.xml
client/app/src/main/res/values/strings.xml

- Tutorials for the start screen and for the requests-on-book screen
- My books screen: *with no book*
- My books screen: *with book*

feat: tutorials
